# This workflow will install Python dependencies, zip the taxonomy files to a taxonomy package and run very basic smoke test with Arelle

name: ISSB-taxonomy smoke test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r CI/requirements.txt
    - name: Test package entrypoints with arelle
      run: |
        zip -r ifrs_sds.zip ifrs_sds
    - name: Test package entrypoints with Arelle
      run: |
        python -u CI/Test_Taxonomy_Package.py ../ifrs_sds.zip
